name: Deploy Next.js to Linegon.com

on:
  workflow_dispatch:
  push:
    branches:
      - linegon
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm@8.14.1

      - name: Install dependencies
        run: npx pnpm@8.14.1 install

      - name: Build Next.js project
        run: npx pnpm@8.14.1 run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SAPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SAPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy to S3
        run: aws s3 sync ./out s3://linegonwebsite --delete
      
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id EVW21JIAJE2VX --paths "/*"
